CREATE OR REPLACE FUNCTION GET_NB_WORKERS(FACTOR NUMBER) RETURN NUMBER IS
    NB_WORKERS NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO NB_WORKERS
    FROM WORKERS_FACTORY_1
    WHERE FACTORY_ID = FACTOR;

    RETURN NB_WORKERS;
END;
/


CREATE OR REPLACE FUNCTION GET_NB_BIG_ROBOTS RETURN NUMBER IS
    NB_ROBOTS NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO NB_ROBOTS
    FROM ROBOTS_HAS_SPARE_PARTS
    GROUP BY ROBOT_ID
    HAVING COUNT(*) > 3;

    RETURN NB_ROBOTS;
END;
/

CREATE OR REPLACE FUNCTION GET_BEST_SUPPLIER RETURN VARCHAR2(100) IS
    BEST_SUPPLIER_NAME VARCHAR2(100);
BEGIN
    SELECT NAME
    INTO BEST_SUPPLIER_NAME
    FROM BEST_SUPPLIERS
    WHERE ROWNUM = 1; -- Sélectionne le premier fournisseur en se basant sur le tri effectué dans la vue BEST_SUPPLIERS

    RETURN BEST_SUPPLIER_NAME;
END;
/