CREATE OR REPLACE PROCEDURE SEED_DATA_WORKERS(NB_WORKERS NUMBER, FACTORY_ID NUMBER) IS
BEGIN
    FOR i IN 1..NB_WORKERS LOOP
        INSERT INTO WORKERS_FACTORY_1 (first_name, last_name, age, first_day, last_day)
        VALUES ('worker_f_' || i, 'worker_l_' || i, FLOOR(DBMS_RANDOM.VALUE(20, 65)), 
        TO_DATE(TRUNC(DBMS_RANDOM.VALUE(TO_CHAR(DATE '2065-01-01','J'), TO_CHAR(DATE '2070-01-01','J'))), 'J'), 
        NULL);
    END LOOP;
END;
/


CREATE OR REPLACE PROCEDURE ADD_NEW_ROBOT(MODEL_NAME VARCHAR2(50)) IS
    FACTORY_ID NUMBER;
BEGIN
    SELECT FACTORY_ID INTO FACTORY_ID
    FROM ROBOTS_FROM_FACTORY
    WHERE ROWNUM = 1; -- Sélectionne le premier factory_id disponible

    INSERT INTO ROBOTS (model)
    VALUES (MODEL_NAME);

    INSERT INTO ROBOTS_FROM_FACTORY (robot_id, factory_id)
    VALUES (LAST_INSERT_ID(), FACTORY_ID);
END;
/

